export const categories = ['All', 'Food', 'Treats', 'Toys', 'Grooming', 'Health', 'Accessories'];
export const petTypes = ['All Pets', 'Dog', 'Cat', 'Bird', 'Small Pet'];

export const products = [
  { 
    id: 1, 
    brand: 'WELL & GOOD',
    name: 'Dental Health Kit for Dogs', 
    category: 'Health', 
    petType: 'Dog',
    price: 549, 
    mrp: 649,
    rating: 4.7, 
    badge: 'Bestseller', 
    badgeColor: 'bg-[#991B1B]',
    tag: 'Dental Care',
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Standard', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '1 kit', price: 549, mrp: 649, discount: 15 }],
    overviewImage: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    description: 'Includes a double-sided toothbrush, finger brush, and vet-approved enzymatic toothpaste. Helps prevent plaque, tartar, and bad breath.',
    reviewsData: { total: 234, average: 4.7, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Dental Care',
    specialDiet: 'Dental Care',
    proteinSource: null,
    weight: '1 Unit',
    discountRange: 15,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: true
  },
  { 
    id: 2, 
    brand: 'WELL & GOOD',
    name: 'Hypoallergenic Deodorizing Wipes for Pets', 
    category: 'Grooming', 
    petType: 'Dog',
    price: 299, 
    mrp: 349,
    rating: 4.6, 
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200', 
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Aloe Vera', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '100 Wipes', price: 299, mrp: 349, discount: 14 }],
    overviewImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    description: 'Gently cleanses and deodorizes paws, coat, and skin. Hypoallergenic, alcohol-free formula enriched with aloe vera and vitamins.',
    reviewsData: { total: 445, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Wipes',
    specialDiet: 'Skin & Coat',
    proteinSource: null,
    weight: '100 Pack',
    discountRange: 14,
    subCategory: 'Dog Wipes',
    isNewArrival: true,
    isBestseller: false
  },
  { 
    id: 3, 
    brand: 'BIOFELINE',
    name: 'BioFeline Malt Paste – Hairball Control', 
    category: 'Health', 
    petType: 'Cat',
    price: 299, 
    mrp: 349,
    rating: 4.6, 
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200', 
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '100 gm', price: 299, mrp: 349, discount: 14 }],
    overviewImage: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    description: 'Vet recommended formula to assist in natural passage of swallowed fur. Helps prevent hairball formations in Persian and long-coated cats.',
    reviewsData: { total: 289, average: 4.6, breakdown: [95, 5, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Sensitive Stomach',
    proteinSource: null,
    weight: '100 gm',
    discountRange: 14,
    subCategory: 'Cat Health',
    isNewArrival: false,
    isBestseller: true
  },
  { 
    id: 4, 
    brand: 'LUXEPAW',
    name: 'Premium Leather Collar + Leash Set', 
    category: 'Accessories', 
    petType: 'Dog',
    price: 2499, 
    mrp: 2999,
    rating: 4.9, 
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200', 
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Tan Brown', img: 'lucide:Circle' }],
    packSizes: [{ size: 'Medium/Large', price: 2499, mrp: 2999, discount: 17 }],
    overviewImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    description: 'Constructed from high-grade full grain genuine leather with soft inner padding. Classy golden steel hardware accents.',
    reviewsData: { total: 78, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Walk Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 17,
    subCategory: 'Collars & Leashes',
    isNewArrival: false,
    isBestseller: true
  },
  { 
    id: 5, 
    brand: 'MAXBONE',
    name: 'Maxbone Blue Walk Accessories Set', 
    category: 'Accessories', 
    petType: 'Dog',
    price: 4499, 
    mrp: 5499,
    rating: 4.8, 
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200', 
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Blue', img: 'lucide:Circle' }],
    packSizes: [{ size: 'Medium/Large', price: 4499, mrp: 5499, discount: 18 }],
    overviewImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    description: 'Includes a padded no-pull harness, matching comfort leash, and dynamic poop bag holder. Extremely premium material designed for all seasons.',
    reviewsData: { total: 67, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Walk Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 18,
    subCategory: 'Harnesses',
    isNewArrival: true,
    isBestseller: false
  },
  { 
    id: 6, 
    brand: 'CAVOLOGY',
    name: 'Cavology Navy Velvet Harness Set', 
    category: 'Accessories', 
    petType: 'Dog',
    price: 2799, 
    mrp: 3499,
    rating: 4.9, 
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200', 
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Navy Velvet', img: 'lucide:Circle' }],
    packSizes: [{ size: 'Medium/Large', price: 2799, mrp: 3499, discount: 20 }],
    overviewImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    description: 'Incredibly soft velvet exterior with high tensile core webbing. Provides max safety while looking incredibly stylish on daily walks.',
    reviewsData: { total: 89, average: 4.9, breakdown: [92, 6, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Walk Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 20,
    subCategory: 'Harnesses',
    isNewArrival: false,
    isBestseller: true
  },
  { 
    id: 7, 
    brand: 'OLLIE XO',
    name: 'Ollie XO Sage Green Harness + Leash Set', 
    category: 'Accessories', 
    petType: 'Dog',
    price: 2299, 
    mrp: 2799,
    rating: 4.9, 
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200', 
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Sage Green', img: 'lucide:Circle' }],
    packSizes: [{ size: 'Medium/Large', price: 2299, mrp: 2799, discount: 18 }],
    overviewImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    description: 'Sleek sage green neoprene harness. Completely water-resistant, odor-resistant, and padded for maximum joint comfort.',
    reviewsData: { total: 176, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Walk Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 18,
    subCategory: 'Harnesses',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 8,
    brand: 'PEDIGREE',
    name: 'Pedigree Adult Dog Food – Chicken & Rice',
    category: 'Food',
    petType: 'Dog',
    price: 2199,
    mrp: 2599,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Drumstick' }],
    packSizes: [{ size: '10 kg', price: 2199, mrp: 2599, discount: 15 }],
    overviewImage: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    description: 'Complete and balanced dry kibbles for adult dogs. Rich in Omega-6, zinc, vitamins, and proteins supporting active daily energy.',
    reviewsData: { total: 1240, average: 4.7, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'High Protein',
    proteinSource: 'Chicken',
    weight: '10 kg',
    discountRange: 15,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 9,
    brand: 'HILL\'S',
    name: 'Hill\'s Science Diet Large Breed Adult',
    category: 'Food',
    petType: 'Dog',
    price: 3499,
    mrp: 3999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Bone' }],
    packSizes: [{ size: '10 kg', price: 3499, mrp: 3999, discount: 13 }],
    overviewImage: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    description: 'Specifically formulated dry food supporting joint health in giant and large breeds. Rich in natural glucosamine and chondroitin.',
    reviewsData: { total: 654, average: 4.9, breakdown: [95, 5, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Joint Care',
    proteinSource: 'Chicken',
    weight: '10 kg',
    discountRange: 13,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 10,
    brand: 'JINX',
    name: 'Jinx Beef Brown Rice & Sweet Potato',
    category: 'Food',
    petType: 'Dog',
    price: 899,
    mrp: 1099,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Beef', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '1.8 kg', price: 899, mrp: 1099, discount: 18 }],
    overviewImage: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    description: 'Premium organic beef recipe with sweet potato and digestive probiotics. Gentle on stomachs and containing zero fillers or wheat.',
    reviewsData: { total: 321, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Sensitive Stomach',
    proteinSource: 'Beef',
    weight: '1.8 kg',
    discountRange: 18,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 11,
    brand: 'RUFF FOOD',
    name: 'Ruff Food – Lamb & Brown Rice',
    category: 'Food',
    petType: 'Dog',
    price: 649,
    mrp: 799,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Lamb', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '1.5 kg', price: 649, mrp: 799, discount: 19 }],
    overviewImage: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    description: 'Natural lamb protein kibble perfect for sensitive stomachs. Contains superfoods and fibers aiding digestion.',
    reviewsData: { total: 234, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Sensitive Stomach',
    proteinSource: 'Lamb',
    weight: '1.5 kg',
    discountRange: 19,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 12,
    brand: 'NUTRIBOWL',
    name: 'Premium Salmon Raw Meal Bowl',
    category: 'Food',
    petType: 'Dog',
    price: 749,
    mrp: 899,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Salmon', img: 'lucide:Fish' }],
    packSizes: [{ size: '1 kg', price: 749, mrp: 899, discount: 17 }],
    overviewImage: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    description: 'Raw freeze-dried wild salmon raw meal. Packed with omega-3 fatty acids for skin, coat shine, and immune support.',
    reviewsData: { total: 184, average: 4.8, breakdown: [84, 16, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Raw Food',
    specialDiet: 'Skin & Coat',
    proteinSource: 'Salmon',
    weight: '1 kg',
    discountRange: 17,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 13,
    brand: 'WHISK',
    name: 'Peanut Butter Banana Bites',
    category: 'Treats',
    petType: 'Dog',
    price: 349,
    mrp: 449,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'PB Banana', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '200 gm', price: 349, mrp: 449, discount: 22 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Perfect natural training treats baked with real creamy peanut butter and sweet bananas. Highly palatable.',
    reviewsData: { total: 187, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: 'Veg',
    lifeStage: 'All Life Stages',
    productType: 'Treats',
    specialDiet: 'Sensitive Stomach',
    proteinSource: 'Peanut',
    weight: '200 gm',
    discountRange: 22,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 14,
    brand: 'SNACKIES',
    name: 'Chicken Cheese Biscuits',
    category: 'Treats',
    petType: 'Dog',
    price: 249,
    mrp: 299,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Cheese', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '250 gm', price: 249, mrp: 299, discount: 17 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Crunchy oven-baked biscuits combining fresh chicken protein and real cheddar cheese. High flavor reward.',
    reviewsData: { total: 445, average: 4.7, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Biscuits',
    specialDiet: null,
    proteinSource: 'Chicken',
    weight: '250 gm',
    discountRange: 17,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 15,
    brand: 'BAKBAKERY',
    name: 'Birthday Cake Dog Treat – Vanilla',
    category: 'Treats',
    petType: 'Dog',
    price: 699,
    mrp: 849,
    rating: 5.0,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Vanilla', img: 'lucide:Cake' }],
    packSizes: [{ size: '1 Cake', price: 699, mrp: 849, discount: 18 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Celebrate special occasions with a dog-friendly vanilla cake frosted with yogurt and colored with beetroot powder.',
    reviewsData: { total: 89, average: 5.0, breakdown: [100, 0, 0, 0, 0], reviews: [] },
    dietType: 'Veg',
    lifeStage: 'All Life Stages',
    productType: 'Special Cake',
    specialDiet: null,
    proteinSource: null,
    weight: '300 gm',
    discountRange: 18,
    subCategory: 'Dog Treats',
    isNewArrival: true,
    isBestseller: false
  },
  {
    id: 16,
    brand: 'BAKBAKERY',
    name: 'Paw Cookie Pack – Chocolate Chip Style',
    category: 'Treats',
    petType: 'Dog',
    price: 399,
    mrp: 499,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Cookie Box', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '6 Pack', price: 399, mrp: 499, discount: 20 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Carob-chip cookies (safe alternative to chocolate) shaped like tiny dog paws. Crispy, delicious, and healthy.',
    reviewsData: { total: 203, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: 'Veg',
    lifeStage: 'All Life Stages',
    productType: 'Cookies',
    specialDiet: null,
    proteinSource: null,
    weight: '150 gm',
    discountRange: 20,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 17,
    brand: 'PAWPLAY',
    name: 'Treat-Dispensing Chew Ball',
    category: 'Toys',
    petType: 'Dog',
    price: 449,
    mrp: 599,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Chew Ball', img: 'lucide:Sparkles' }],
    packSizes: [{ size: 'One Size', price: 449, mrp: 599, discount: 25 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Tough rubber ball that dispenses kibbles slowly as they play. Combats boredom and prevents fast eating.',
    reviewsData: { total: 93, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 25,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 18,
    brand: 'PETJOY',
    name: 'Colourful Rope Toy Bundle (7pc)',
    category: 'Toys',
    petType: 'Dog',
    price: 599,
    mrp: 799,
    rating: 4.5,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: '7pc Set', img: 'lucide:Layers' }],
    packSizes: [{ size: '7 Pack', price: 599, mrp: 799, discount: 25 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Cotton braided rope pack for interactive tug of war and teeth cleaning. Incredibly sturdy and machine washable.',
    reviewsData: { total: 156, average: 4.5, breakdown: [65, 25, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 25,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 19,
    brand: 'SPLASHPAW',
    name: 'Summer Splash Pool Toy Set',
    category: 'Toys',
    petType: 'Dog',
    price: 849,
    mrp: 999,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Waterproof Set', img: 'lucide:Activity' }],
    packSizes: [{ size: '3 toys', price: 849, mrp: 999, discount: 15 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Floats on water! Floating bone, fetch ring, and rubber dumbbell. Made for high energy retrievers who swim.',
    reviewsData: { total: 74, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 20,
    brand: 'TALL TAILS',
    name: 'Tall Tails Duck Squeaky Toy',
    category: 'Toys',
    petType: 'Dog',
    price: 649,
    mrp: 799,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Duck', img: 'lucide:Sparkles' }],
    packSizes: [{ size: 'Medium', price: 649, mrp: 799, discount: 19 }],
    overviewImage: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    description: 'Double stitched canvas mallard duck toy with internal squeaker. Extremely soft, satisfies natural fetch drive.',
    reviewsData: { total: 91, average: 4.6, breakdown: [70, 20, 11, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 19,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 21,
    brand: 'BRAINPAW',
    name: 'Interactive Puzzle Toy Set',
    category: 'Toys',
    petType: 'Dog',
    price: 799,
    mrp: 999,
    rating: 4.4,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Level 1', img: 'lucide:Layers' }],
    packSizes: [{ size: 'Level 1', price: 799, mrp: 999, discount: 20 }],
    overviewImage: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    description: 'Treat dispensing intelligence developer. Helps keep active dogs engaged and boosts mental focus.',
    reviewsData: { total: 78, average: 4.4, breakdown: [68, 22, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'Adult',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 20,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 22,
    brand: 'DOGX',
    name: 'DOGX All Terrain Pet Shampoo 1L',
    category: 'Grooming',
    petType: 'Dog',
    price: 899,
    mrp: 1099,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Deep Clean', img: 'lucide:Bath' }],
    packSizes: [{ size: '1 Litre', price: 899, mrp: 1099, discount: 18 }],
    overviewImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    description: 'Professional grade large volume shampoo. Targets stubborn mud, dirt, and wet-dog smells leaving a clean cedar fragrance.',
    reviewsData: { total: 203, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Shampoo',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 18,
    subCategory: 'Shampoos',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 23,
    brand: 'WILD ONE',
    name: 'Wild One Conditioning Shampoo',
    category: 'Grooming',
    petType: 'Dog',
    price: 699,
    mrp: 849,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Grapefruit', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '500 ml', price: 699, mrp: 849, discount: 18 }],
    overviewImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    description: 'Hypoallergenic 2-in-1 shampoo and conditioner made with organic extracts. Nourishes dry hair and leaves a sleek coat.',
    reviewsData: { total: 156, average: 4.8, breakdown: [85, 11, 4, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Shampoo',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 18,
    subCategory: 'Shampoos',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 24,
    brand: 'PETESSENTIALS',
    name: 'Pet Grooming Glove',
    category: 'Grooming',
    petType: 'Dog',
    price: 349,
    mrp: 449,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Blue Glove', img: 'lucide:Hand' }],
    packSizes: [{ size: '1 Pair', price: 349, mrp: 449, discount: 22 }],
    overviewImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    description: 'Perfect deshedding glove with silicone tips. Trap loose undercoat fur as you pet them, makes coat shine.',
    reviewsData: { total: 312, average: 4.7, breakdown: [80, 15, 7, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Grooming Tool',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 22,
    subCategory: 'Brushes',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 25,
    brand: 'ALWAYS PUPS',
    name: 'Ultra-Moisturising Paw Balm',
    category: 'Grooming',
    petType: 'Dog',
    price: 399,
    mrp: 499,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Cocoa Butter', img: 'lucide:Flower' }],
    packSizes: [{ size: '50 gm', price: 399, mrp: 499, discount: 20 }],
    overviewImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    description: 'Moisturizes dry, cracked nose and pads instantly. Completely organic and safe to lick.',
    reviewsData: { total: 178, average: 4.8, breakdown: [82, 16, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Balm',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 20,
    subCategory: 'Balms',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 26,
    brand: 'TailCircle',
    name: 'Automatic Pet Water Fountain - 2.5L',
    category: 'Accessories',
    petType: 'Cat',
    price: 2499,
    mrp: 3299,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'White Flow', img: 'lucide:RefreshCw' }],
    packSizes: [{ size: '1 unit', price: 2499, mrp: 3299, discount: 24 }],
    overviewImage: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=200',
    description: 'Encourages cats and small pets to hydrate more with clean running water. Quiet motor.',
    reviewsData: { total: 78, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Bowls',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 24,
    subCategory: 'Bowls',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 27,
    brand: 'ComfortPaw',
    name: 'Orthopedic Memory Foam Pet Bed (Large)',
    category: 'Accessories',
    petType: 'Dog',
    price: 2499,
    mrp: 3125,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Slate Gray', img: 'lucide:Home' }],
    packSizes: [{ size: 'Large', price: 2499, mrp: 3125, discount: 20 }],
    overviewImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    description: 'Premium medical-grade memory foam. Supports bones, reduces joint friction, washable cover.',
    reviewsData: { total: 158, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'Senior',
    productType: 'Bedding',
    specialDiet: 'Joint Care',
    proteinSource: null,
    weight: null,
    discountRange: 20,
    subCategory: 'Beds',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 28,
    brand: 'TravelPaw',
    name: 'Waterproof Pet Car Seat Protection Cover',
    category: 'Accessories',
    petType: 'Dog',
    price: 1599,
    mrp: 1880,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Standard Black', img: 'lucide:Shield' }],
    packSizes: [{ size: 'Universal size', price: 1599, mrp: 1880, discount: 15 }],
    overviewImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    description: 'Durable seat cover protecting your car from dirt, shed fur, claws and wet paws.',
    reviewsData: { total: 76, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Travel Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Travel',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 29,
    brand: 'ORIJEN',
    name: 'Orijen Fit & Trim Weight Control Dog Food',
    category: 'Food',
    petType: 'Dog',
    price: 3899,
    mrp: 4599,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Scale' }],
    packSizes: [{ size: '10 kg', price: 3899, mrp: 4599, discount: 15 }],
    description: 'Grain-free weight management dry food rich in lean proteins from chicken, turkey, and fish. Low in fat and carbs.',
    reviewsData: { total: 112, average: 4.8, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Weight Management',
    proteinSource: 'Chicken',
    weight: '10 kg',
    discountRange: 15,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 30,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Golden Retriever Adult Food',
    category: 'Food',
    petType: 'Dog',
    price: 4999,
    mrp: 5499,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '12 kg', price: 4999, mrp: 5499, discount: 9 }],
    description: 'Tailored nutrition for purebred Golden Retrievers. Supports skin and coat health, heart health, and weight management.',
    reviewsData: { total: 489, average: 4.9, breakdown: [95, 5, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Breed Specific',
    proteinSource: 'Chicken',
    weight: '12 kg',
    discountRange: 9,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 31,
    brand: 'ACANA',
    name: 'Acana Wild Coast Fish-Based Dog Food',
    category: 'Food',
    petType: 'Dog',
    price: 3299,
    mrp: 3799,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Wild Coast', img: 'lucide:Fish' }],
    packSizes: [{ size: '9.7 kg', price: 3299, mrp: 3799, discount: 13 }],
    description: 'Fish-based formula rich in omega fatty acids for a shiny coat and healthy skin. Made with sustainably sourced wild fish.',
    reviewsData: { total: 95, average: 4.7, breakdown: [75, 15, 10, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Dry Food',
    specialDiet: 'Sensitive Skin',
    proteinSource: 'Fish',
    weight: '9.7 kg',
    discountRange: 13,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 32,
    brand: 'ARDEN GRANGE',
    name: 'Arden Grange Sensitive Light - Weight Management',
    category: 'Food',
    petType: 'Dog',
    price: 2799,
    mrp: 3199,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Sensitive Light', img: 'lucide:Leaf' }],
    packSizes: [{ size: '6 kg', price: 2799, mrp: 3199, discount: 12 }],
    description: 'Portion-controlled dietetic food formulated for dogs needing weight management or showing digestive sensitivity.',
    reviewsData: { total: 84, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Weight Management',
    proteinSource: 'White Fish',
    weight: '6 kg',
    discountRange: 12,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 33,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Pug Adult Food',
    category: 'Food',
    petType: 'Dog',
    price: 1899,
    mrp: 2199,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '3 kg', price: 1899, mrp: 2199, discount: 13 }],
    description: 'Specifically designed kibble shape for Pugs. Supports muscle tone and healthy folds.',
    reviewsData: { total: 154, average: 4.8, breakdown: [85, 10, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Breed Specific',
    proteinSource: 'Chicken',
    weight: '3 kg',
    discountRange: 13,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 34,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Shih Tzu Adult Food',
    category: 'Food',
    petType: 'Dog',
    price: 1799,
    mrp: 1999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '3 kg', price: 1799, mrp: 1999, discount: 10 }],
    description: 'Promotes healthy skin, long silky coat, and reduces dental plaque buildup in adult Shih Tzus.',
    reviewsData: { total: 198, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Breed Specific',
    proteinSource: 'Chicken',
    weight: '3 kg',
    discountRange: 10,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 35,
    brand: 'TASTE OF THE WILD',
    name: 'Taste of the Wild High Energy Formula',
    category: 'Food',
    petType: 'Dog',
    price: 3699,
    mrp: 4199,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Wetlands', img: 'lucide:Flame' }],
    packSizes: [{ size: '12 kg', price: 3699, mrp: 4199, discount: 11 }],
    description: 'High energy density formula with real roasted fowl. Excellent source of wild fowl protein for active dogs.',
    reviewsData: { total: 145, average: 4.8, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'High Protein',
    proteinSource: 'Duck',
    weight: '12 kg',
    discountRange: 11,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 36,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin German Shepherd Adult Food',
    category: 'Food',
    petType: 'Dog',
    price: 5299,
    mrp: 5799,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '12 kg', price: 5299, mrp: 5799, discount: 8 }],
    description: 'Tailored recipe to support digestion and bone/joint health of athletic German Shepherds.',
    reviewsData: { total: 312, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Breed Specific',
    proteinSource: 'Chicken',
    weight: '12 kg',
    discountRange: 8,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 37,
    brand: 'ORIJEN',
    name: 'Orijen Tundra Giant Breed Dog Food',
    category: 'Food',
    petType: 'Dog',
    price: 5999,
    mrp: 6699,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Tundra', img: 'lucide:Award' }],
    packSizes: [{ size: '11.4 kg', price: 5999, mrp: 6699, discount: 10 }],
    description: 'Giant-breed tailored high-protein food. Feature fresh boar, goat, venison, and arctic char.',
    reviewsData: { total: 110, average: 4.9, breakdown: [92, 6, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'High Protein',
    proteinSource: 'Mixed Wild Meat',
    weight: '11.4 kg',
    discountRange: 10,
    subCategory: 'Dog Dry Food',
    isNewArrival: true,
    isBestseller: false
  },
  {
    id: 38,
    brand: 'FARMINA',
    name: 'Farmina N&D Ancestral Grain Muscle Formula',
    category: 'Food',
    petType: 'Dog',
    price: 4399,
    mrp: 4999,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Chicken & Pomegranate', img: 'lucide:Activity' }],
    packSizes: [{ size: '12 kg', price: 4399, mrp: 4999, discount: 12 }],
    description: 'Ancestral grain muscle building formula with chicken and pomegranate. Builds and maintains lean muscle.',
    reviewsData: { total: 178, average: 4.8, breakdown: [85, 12, 3, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Lean Muscle',
    proteinSource: 'Chicken',
    weight: '12 kg',
    discountRange: 12,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 39,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Medium Adult',
    category: 'Food',
    petType: 'Dog',
    price: 3499,
    mrp: 3899,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1589965716319-4aa04041b6ec?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Medium Adult', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '10 kg', price: 3499, mrp: 3899, discount: 10 }],
    description: 'Helps support the medium breed dog’s natural defenses and immunity. Promotes optimal digestability.',
    reviewsData: { total: 205, average: 4.7, breakdown: [75, 20, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Immunity Support',
    proteinSource: 'Chicken',
    weight: '10 kg',
    discountRange: 10,
    subCategory: 'Dog Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 40,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Hairball Care Cat Food',
    category: 'Food',
    petType: 'Cat',
    price: 1549,
    mrp: 1799,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Hairball Care', img: 'lucide:Cat' }],
    packSizes: [{ size: '2 kg', price: 1549, mrp: 1799, discount: 13 }],
    description: 'Dry cat food specially formulated to help prevent hairball buildup in long hair cats like Persians.',
    reviewsData: { total: 312, average: 4.8, breakdown: [85, 12, 3, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Hairball Control',
    proteinSource: 'Poultry',
    weight: '2 kg',
    discountRange: 13,
    subCategory: 'Cat Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 41,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Maine Coon Adult Cat Food',
    category: 'Food',
    petType: 'Cat',
    price: 2599,
    mrp: 2999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Maine Coon', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '4 kg', price: 2599, mrp: 2999, discount: 13 }],
    description: 'Enriched with joint supplements to support large cat skeletal structure. Specific cube kibble for Maine Coons.',
    reviewsData: { total: 148, average: 4.9, breakdown: [92, 6, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Breed Specific',
    proteinSource: 'Poultry',
    weight: '4 kg',
    discountRange: 13,
    subCategory: 'Cat Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 42,
    brand: 'ORIJEN',
    name: 'Orijen Six Fish High Protein Cat Food',
    category: 'Food',
    petType: 'Cat',
    price: 1999,
    mrp: 2299,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Six Fish', img: 'lucide:Fish' }],
    packSizes: [{ size: '1.8 kg', price: 1999, mrp: 2299, discount: 13 }],
    description: 'Unmatched raw energy support. Made with mackerel, herring, flounder, redfish, monkfish, and hake.',
    reviewsData: { total: 201, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Dry Food',
    specialDiet: 'High Protein',
    proteinSource: 'Fish',
    weight: '1.8 kg',
    discountRange: 13,
    subCategory: 'Cat Dry Food',
    isNewArrival: true,
    isBestseller: true
  },
  {
    id: 43,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin British Shorthair Adult Cat Food',
    category: 'Food',
    petType: 'Cat',
    price: 2399,
    mrp: 2699,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'British Shorthair', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '4 kg', price: 2399, mrp: 2699, discount: 11 }],
    description: 'Maintains health of dense bones and heavy muscles. Supports weight control and heart health.',
    reviewsData: { total: 112, average: 4.8, breakdown: [80, 15, 7, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Breed Specific',
    proteinSource: 'Poultry',
    weight: '4 kg',
    discountRange: 11,
    subCategory: 'Cat Dry Food',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 44,
    brand: 'ROYAL CANIN',
    name: 'Royal Canin Indoor Adult Cat Food',
    category: 'Food',
    petType: 'Cat',
    price: 1399,
    mrp: 1599,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Indoor Adult', img: 'lucide:Home' }],
    packSizes: [{ size: '2 kg', price: 1399, mrp: 1599, discount: 12 }],
    description: 'Supports indoor digestive health and reduces litter box odor. Perfect for calm indoor cats.',
    reviewsData: { total: 245, average: 4.7, breakdown: [75, 20, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Dry Food',
    specialDiet: 'Indoor Support',
    proteinSource: 'Poultry',
    weight: '2 kg',
    discountRange: 12,
    subCategory: 'Cat Dry Food',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 45,
    brand: 'BARKING HEADS',
    name: 'Barking Heads Training Treats',
    category: 'Treats',
    petType: 'Dog',
    price: 349,
    mrp: 399,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Chicken', img: 'lucide:Drumstick' }],
    packSizes: [{ size: '150 gm', price: 349, mrp: 399, discount: 12 }],
    description: 'Perfect bite-sized pieces for dog training rewards. High meat percentage and extremely delicious.',
    reviewsData: { total: 156, average: 4.8, breakdown: [85, 10, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Treats',
    specialDiet: 'Low Calorie',
    proteinSource: 'Chicken',
    weight: '150 gm',
    discountRange: 12,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 46,
    brand: 'PEDIGREE',
    name: 'Pedigree Dentastix Dental Chews',
    category: 'Treats',
    petType: 'Dog',
    price: 199,
    mrp: 249,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Daily Stick', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '7 sticks', price: 199, mrp: 249, discount: 20 }],
    description: 'Unique X-shape design. Promotes dental hygiene and prevents plaque/tartar buildup.',
    reviewsData: { total: 645, average: 4.8, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Dental Sticks',
    specialDiet: 'Dental Care',
    proteinSource: 'Beef',
    weight: '7 Sticks',
    discountRange: 20,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 47,
    brand: 'ZOË',
    name: 'Zoë Peanut Butter & Coconut Dog Treats',
    category: 'Treats',
    petType: 'Dog',
    price: 299,
    mrp: 349,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'PB & Coconut', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '150 gm', price: 299, mrp: 349, discount: 14 }],
    description: 'Rich, grain-free cookies with real peanut butter and coconut oil. Soft-baked texture.',
    reviewsData: { total: 98, average: 4.7, breakdown: [75, 20, 5, 0, 0], reviews: [] },
    dietType: 'Veg',
    lifeStage: 'All Life Stages',
    productType: 'Treats',
    specialDiet: 'Skin & Coat',
    proteinSource: 'Peanut',
    weight: '150 gm',
    discountRange: 14,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 48,
    brand: 'BARK & BEYOND',
    name: 'Low Calorie Small Breed Training Treats',
    category: 'Treats',
    petType: 'Dog',
    price: 320,
    mrp: 380,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Rabbit', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '120 gm', price: 320, mrp: 380, discount: 15 }],
    description: 'Extremely small size, perfect for puppies, Beagles, and toy breeds. Less than 2 kcal per treat.',
    reviewsData: { total: 76, average: 4.7, breakdown: [72, 20, 8, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Puppy',
    productType: 'Treats',
    specialDiet: 'Low Calorie',
    proteinSource: 'Rabbit',
    weight: '120 gm',
    discountRange: 15,
    subCategory: 'Dog Treats',
    isNewArrival: true,
    isBestseller: false
  },
  {
    id: 49,
    brand: 'SNACKIES',
    name: 'Snackies Low Fat Dental Chews',
    category: 'Treats',
    petType: 'Dog',
    price: 279,
    mrp: 329,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Spearmint', img: 'lucide:Activity' }],
    packSizes: [{ size: '10 Pack', price: 279, mrp: 329, discount: 15 }],
    description: 'Fresh breath dental treats containing chlorophyll. 0% added fat, ideal for Pugs and less-active dogs.',
    reviewsData: { total: 64, average: 4.6, breakdown: [65, 25, 10, 0, 0], reviews: [] },
    dietType: 'Veg',
    lifeStage: 'All Life Stages',
    productType: 'Dental Sticks',
    specialDiet: 'Weight Management',
    proteinSource: null,
    weight: '10 Pack',
    discountRange: 15,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 50,
    brand: 'HIMALAYA',
    name: 'Freeze-Dried Beef Liver Treats',
    category: 'Treats',
    petType: 'Dog',
    price: 499,
    mrp: 599,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Beef Liver', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '80 gm', price: 499, mrp: 599, discount: 16 }],
    description: '100% pure freeze-dried beef liver with absolutely no additives. Pure protein hit for high energy dogs.',
    reviewsData: { total: 152, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Treats',
    specialDiet: 'High Protein',
    proteinSource: 'Beef',
    weight: '80 gm',
    discountRange: 16,
    subCategory: 'Dog Treats',
    isNewArrival: true,
    isBestseller: true
  },
  {
    id: 51,
    brand: 'CHEWERS',
    name: 'Chewers Premium Protein Dog Treats',
    category: 'Treats',
    petType: 'Dog',
    price: 379,
    mrp: 449,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'High Protein', img: 'lucide:Activity' }],
    packSizes: [{ size: '200 gm', price: 379, mrp: 449, discount: 15 }],
    description: 'Jerky bars loaded with amino acids. Rebuilds muscle fibers after intense workouts. Perfect for Rottweilers.',
    reviewsData: { total: 88, average: 4.8, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'Adult',
    productType: 'Treats',
    specialDiet: 'High Protein',
    proteinSource: 'Chicken & Fish',
    weight: '200 gm',
    discountRange: 15,
    subCategory: 'Dog Treats',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 52,
    brand: 'SHEBA',
    name: 'Sheba Melty Soft Cat Treats',
    category: 'Treats',
    petType: 'Cat',
    price: 199,
    mrp: 249,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Tuna & Salmon', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '4 sticks', price: 199, mrp: 249, discount: 20 }],
    description: 'Irresistible creamy puree cat treats. Feed directly by hand to build deep bonds.',
    reviewsData: { total: 421, average: 4.9, breakdown: [95, 5, 0, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Treats',
    specialDiet: 'Sensitive Stomach',
    proteinSource: 'Tuna',
    weight: '4 Sticks',
    discountRange: 20,
    subCategory: 'Cat Treats',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 53,
    brand: 'KONG',
    name: 'KONG Extreme Heavy Duty Rubber Chew Toy',
    category: 'Toys',
    petType: 'Dog',
    price: 999,
    mrp: 1199,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Black Extreme', img: 'lucide:Shield' }],
    packSizes: [{ size: 'Large', price: 999, mrp: 1199, discount: 16 }],
    description: 'Super-sturdy black rubber compound built for power chewers like Rottweilers and GSDs.',
    reviewsData: { total: 541, average: 4.9, breakdown: [95, 5, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 54,
    brand: 'CHUCKIT!',
    name: 'Chuckit! Ultra Rubber Fetch Ball',
    category: 'Toys',
    petType: 'Dog',
    price: 549,
    mrp: 649,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Orange', img: 'lucide:Dribbble' }],
    packSizes: [{ size: 'Medium (2-Pack)', price: 549, mrp: 649, discount: 15 }],
    description: 'Designed for the most demanding fetch games. Floating, highly visible, and durable bounce.',
    reviewsData: { total: 312, average: 4.8, breakdown: [82, 16, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 55,
    brand: 'WEST PAW',
    name: 'West Paw Zogoflex Flexible Frisbee',
    category: 'Toys',
    petType: 'Dog',
    price: 1199,
    mrp: 1399,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Lime Green', img: 'lucide:Disc' }],
    packSizes: [{ size: 'One Size', price: 1199, mrp: 1399, discount: 14 }],
    description: 'High flying, soft aerodynamic disc toy. Friendly on teeth and gums, floats in water.',
    reviewsData: { total: 105, average: 4.7, breakdown: [75, 20, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 14,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 56,
    brand: 'BOODA',
    name: 'Booda Fresh Cotton Tug & Rope Toy',
    category: 'Toys',
    petType: 'Dog',
    price: 499,
    mrp: 599,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Multi-Color', img: 'lucide:Menu' }],
    packSizes: [{ size: '3-Knot Large', price: 499, mrp: 599, discount: 16 }],
    description: 'Tough braided cotton fibres. Great for interactive tug and cleaning dog teeth while chewing.',
    reviewsData: { total: 245, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 57,
    brand: 'OUTWARD HOUND',
    name: 'Outward Hound Interactive Sniffing Mat',
    category: 'Toys',
    petType: 'Dog',
    price: 1299,
    mrp: 1599,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Garden Mat', img: 'lucide:Grid' }],
    packSizes: [{ size: 'Large Mat', price: 1299, mrp: 1599, discount: 18 }],
    description: 'Stimulates your dog’s natural foraging instincts. Hide kibbles or treats to make them sniff.',
    reviewsData: { total: 95, average: 4.8, breakdown: [82, 12, 6, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 18,
    subCategory: 'Dog Toys',
    isNewArrival: true,
    isBestseller: false
  },
  {
    id: 58,
    brand: 'NINA OTTOSSON',
    name: 'Nina Ottosson Treat Puzzle Feeder Toy',
    category: 'Toys',
    petType: 'Dog',
    price: 1499,
    mrp: 1799,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Level 2', img: 'lucide:Layers' }],
    packSizes: [{ size: 'Standard Size', price: 1499, mrp: 1799, discount: 16 }],
    description: 'Award-winning interactive intelligence developer. Keeps dogs focused and mentally engaged.',
    reviewsData: { total: 203, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'Adult',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 59,
    brand: 'PETSTAGES',
    name: 'Petstages Orka Soft Plush Squeaker Toy',
    category: 'Toys',
    petType: 'Dog',
    price: 449,
    mrp: 499,
    rating: 4.5,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Plush Teddy', img: 'lucide:Heart' }],
    packSizes: [{ size: 'Medium', price: 449, mrp: 499, discount: 10 }],
    description: 'Soft fabric textures combined with a squeaker. Ideal comfort toy for toy breeds and Pugs.',
    reviewsData: { total: 110, average: 4.5, breakdown: [65, 25, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 10,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 60,
    brand: 'KONG',
    name: 'KONG Flyer Flexible Running Rubber Disc',
    category: 'Toys',
    petType: 'Dog',
    price: 899,
    mrp: 999,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1537151608804-ea2f1fa502de?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Flyer Red', img: 'lucide:Disc' }],
    packSizes: [{ size: 'One Size', price: 899, mrp: 999, discount: 10 }],
    description: 'Made of soft, flexible natural rubber. Perfect for extreme fetch games and active running chases.',
    reviewsData: { total: 145, average: 4.8, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 10,
    subCategory: 'Dog Toys',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 61,
    brand: 'FITPAWS',
    name: 'FitPAWS Professional Dog Agility Kit',
    category: 'Toys',
    petType: 'Dog',
    price: 3499,
    mrp: 3999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Agility Set', img: 'lucide:Flag' }],
    packSizes: [{ size: '6 Hurdle Set', price: 3499, mrp: 3999, discount: 12 }],
    description: 'Includes hurdles, agility cones, and jump bars. Boosts cardiovascular endurance and focus.',
    reviewsData: { total: 47, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'Adult',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 12,
    subCategory: 'Dog Toys',
    isNewArrival: true,
    isBestseller: false
  },
  {
    id: 62,
    brand: 'CATIT',
    name: 'Catit Senses Hunting Circuit & Toy Set',
    category: 'Toys',
    petType: 'Cat',
    price: 1299,
    mrp: 1499,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Track Circuit', img: 'lucide:RefreshCw' }],
    packSizes: [{ size: '1 Circuit', price: 1299, mrp: 1499, discount: 13 }],
    description: 'Speed ball track that appeals to a cat’s natural hunting instincts. Hours of interactive batting.',
    reviewsData: { total: 320, average: 4.8, breakdown: [80, 18, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Toy',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 13,
    subCategory: 'Cat Toys',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 63,
    brand: 'FURMINATOR',
    name: 'Furminator Undercoat De-shedding Tool',
    category: 'Grooming',
    petType: 'Dog',
    price: 1899,
    mrp: 2299,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Long Hair Tool', img: 'lucide:Scissors' }],
    packSizes: [{ size: 'Medium/Large', price: 1899, mrp: 2299, discount: 17 }],
    description: 'Undercoat shedding rake designed to pull loose dead hair without damaging topcoat. Crucial for heavy shedders.',
    reviewsData: { total: 754, average: 4.9, breakdown: [95, 5, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Brush',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 17,
    subCategory: 'Brushes',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 64,
    brand: 'TROPICLEAN',
    name: 'TropiClean Long Coat Conditioning Shampoo',
    category: 'Grooming',
    petType: 'Dog',
    price: 649,
    mrp: 749,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Coconut & Papaya', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '473 ml', price: 649, mrp: 749, discount: 13 }],
    description: 'Cleanses, detangles, and conditions thick, long coats. Leaves a lasting sweet fragrance.',
    reviewsData: { total: 184, average: 4.8, breakdown: [82, 15, 3, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Shampoo',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 13,
    subCategory: 'Shampoos',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 65,
    brand: 'WELL & GOOD',
    name: 'Well & Good Natural Paw & Nose Balm',
    category: 'Grooming',
    petType: 'Dog',
    price: 349,
    mrp: 399,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Shea Butter', img: 'lucide:Flower' }],
    packSizes: [{ size: '60 gm', price: 349, mrp: 399, discount: 12 }],
    description: 'Enriched with organic shea butter and coconut oil. Soothes dry, cracked paws and noses instantly.',
    reviewsData: { total: 112, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Balm',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 12,
    subCategory: 'Balms',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 66,
    brand: 'EARTHBATH',
    name: 'Earthbath Short Coat Grooming Brush',
    category: 'Grooming',
    petType: 'Dog',
    price: 499,
    mrp: 599,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Soft Bristle', img: 'lucide:Sparkles' }],
    packSizes: [{ size: 'Medium', price: 499, mrp: 599, discount: 16 }],
    description: 'Soft natural bristle brush. Safely collects loose hairs from short coat breeds like Beagles and Pugs.',
    reviewsData: { total: 84, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Brush',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Brushes',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 67,
    brand: 'EARTHBATH',
    name: 'Earthbath Facial Fold Wipes',
    category: 'Grooming',
    petType: 'Dog',
    price: 399,
    mrp: 449,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Unscented', img: 'lucide:Smile' }],
    packSizes: [{ size: '80 pack', price: 399, mrp: 449, discount: 11 }],
    description: 'Specifically pH-balanced to wipe and clean facial wrinkles and skin folds in flat-faced dogs like Pugs.',
    reviewsData: { total: 201, average: 4.8, breakdown: [82, 16, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Wipes',
    specialDiet: 'Sensitive Skin',
    proteinSource: null,
    weight: '80 Wipes',
    discountRange: 11,
    subCategory: 'Dog Wipes',
    isNewArrival: true,
    isBestseller: true
  },
  {
    id: 68,
    brand: 'EYE ENVY',
    name: 'Eye Envy Tear Stain Cleaner Kit',
    category: 'Grooming',
    petType: 'Dog',
    price: 899,
    mrp: 999,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Clean Gel', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '120 ml', price: 899, mrp: 999, discount: 10 }],
    description: 'Enzymatic gel solution that gently dissolves reddish tear stains and buildup in Pugs and Shih Tzus.',
    reviewsData: { total: 64, average: 4.7, breakdown: [75, 20, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Stain Remover',
    specialDiet: 'Eye Care',
    proteinSource: null,
    weight: null,
    discountRange: 10,
    subCategory: 'Shampoos',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 69,
    brand: 'FURMINATOR',
    name: 'Furminator Professional Grooming Comb',
    category: 'Grooming',
    petType: 'Dog',
    price: 549,
    mrp: 649,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Steel Pins', img: 'lucide:Menu' }],
    packSizes: [{ size: 'Medium Comb', price: 549, mrp: 649, discount: 15 }],
    description: 'Rounded steel teeth that rotate to prevent hair pulling. Detangles long-haired Shih Tzu coats smoothly.',
    reviewsData: { total: 118, average: 4.7, breakdown: [80, 12, 8, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Comb',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Brushes',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 70,
    brand: 'TROPICLEAN',
    name: 'TropiClean Silk Protein Conditioner',
    category: 'Grooming',
    petType: 'Dog',
    price: 599,
    mrp: 699,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Original Silk', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '355 ml', price: 599, mrp: 699, discount: 14 }],
    description: 'Silk extract cream conditioner. Detangles mats, reduces frizz, and leaves coats extremely shiny.',
    reviewsData: { total: 89, average: 4.8, breakdown: [85, 10, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Conditioner',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 14,
    subCategory: 'Shampoos',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 71,
    brand: 'WAHL',
    name: 'Wahl Basic Clean Lavender Pet Shampoo',
    category: 'Grooming',
    petType: 'Dog',
    price: 449,
    mrp: 549,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Lavender', img: 'lucide:Flower2' }],
    packSizes: [{ size: '500 ml', price: 449, mrp: 549, discount: 18 }],
    description: 'Basic clean shampoo with soothing lavender extracts. Cleans dirt and leaves the coat refreshed.',
    reviewsData: { total: 312, average: 4.7, breakdown: [75, 20, 7, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Shampoo',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 18,
    subCategory: 'Shampoos',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 72,
    brand: 'HERTZKO',
    name: 'Hertzko Self-Cleaning Slicker Brush',
    category: 'Grooming',
    petType: 'Cat',
    price: 849,
    mrp: 999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Classic Slicker', img: 'lucide:Sparkles' }],
    packSizes: [{ size: 'Standard Size', price: 849, mrp: 999, discount: 15 }],
    description: 'Slicker brush that gently removes loose undercoat hair in long hair cats like Maine Coons and Persians.',
    reviewsData: { total: 452, average: 4.9, breakdown: [92, 6, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Brush',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Brushes',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 73,
    brand: 'BEAPHAR',
    name: 'Glucosamine Chondroitin Joint Supplements',
    category: 'Health',
    petType: 'Dog',
    price: 899,
    mrp: 999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Joint Care Tablets', img: 'lucide:ShieldCheck' }],
    packSizes: [{ size: '60 Tablets', price: 899, mrp: 999, discount: 10 }],
    description: 'Veterinary recommended joint support tablets containing glucosamine, chondroitin, and MSM.',
    reviewsData: { total: 245, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Joint Care',
    proteinSource: 'Shellfish',
    weight: '60 tabs',
    discountRange: 10,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 74,
    brand: 'NORDIC NATURALS',
    name: 'Nordic Naturals Omega-3 Fish Oil',
    category: 'Health',
    petType: 'Dog',
    price: 1499,
    mrp: 1699,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Wild Anchovy Oil', img: 'lucide:Fish' }],
    packSizes: [{ size: '237 ml', price: 1499, mrp: 1699, discount: 12 }],
    description: 'Pure liquid omega-3 oil harvested from wild anchovies. Promotes skin health, shiny coats, and joint mobility.',
    reviewsData: { total: 178, average: 4.9, breakdown: [92, 6, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Skin & Coat',
    proteinSource: 'Fish Oil',
    weight: '237 ml',
    discountRange: 12,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 75,
    brand: 'PET NATURALS',
    name: 'Pet Naturals Weight Control Supplement',
    category: 'Health',
    petType: 'Dog',
    price: 649,
    mrp: 749,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Chews', img: 'lucide:Activity' }],
    packSizes: [{ size: '60 Chews', price: 649, mrp: 749, discount: 13 }],
    description: 'L-Carnitine chews designed to boost metabolism and assist in burning fat in obese dogs.',
    reviewsData: { total: 84, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: 'Veg',
    lifeStage: 'Adult',
    productType: 'Supplements',
    specialDiet: 'Weight Management',
    proteinSource: null,
    weight: '60 tabs',
    discountRange: 13,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 76,
    brand: 'VETOQUINOL',
    name: 'Vetoquinol Mobility Support Joint Paste',
    category: 'Health',
    petType: 'Dog',
    price: 799,
    mrp: 899,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Joint Paste', img: 'lucide:Activity' }],
    packSizes: [{ size: '100 gm', price: 799, mrp: 899, discount: 11 }],
    description: 'Palatable nutritional gel supporting mobility and limb rehabilitation in active/working dogs.',
    reviewsData: { total: 64, average: 4.8, breakdown: [80, 18, 2, 0, 0], reviews: [] },
    dietType: 'Non-Veg',
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Joint Care',
    proteinSource: 'Green-lipped Mussel',
    weight: '100 gm',
    discountRange: 11,
    subCategory: 'Dog Health',
    isNewArrival: true,
    isBestseller: false
  },
  {
    id: 77,
    brand: 'VET\'S BEST',
    name: 'Vet\'s Best Ear Relief Clean Wash',
    category: 'Health',
    petType: 'Dog',
    price: 499,
    mrp: 599,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Aloe Formula', img: 'lucide:Smile' }],
    packSizes: [{ size: '118 ml', price: 499, mrp: 599, discount: 16 }],
    description: 'Relieves ear itching, yeast infections, and removes odor. Critical for floppy-eared dogs like Beagles.',
    reviewsData: { total: 187, average: 4.7, breakdown: [78, 18, 4, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Ear Cleaner',
    specialDiet: 'Ear Care',
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 78,
    brand: 'VETCHOICE',
    name: 'Breathe-Easy Airway Support Syrup',
    category: 'Health',
    petType: 'Dog',
    price: 549,
    mrp: 649,
    rating: 4.6,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Airway Syrup', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '100 ml', price: 549, mrp: 649, discount: 15 }],
    description: 'Soothing natural syrup that supports respiratory pathways and breathing in flat-faced Pugs.',
    reviewsData: { total: 54, average: 4.6, breakdown: [70, 20, 10, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Breathing Support',
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 79,
    brand: 'TROPICLEAN',
    name: 'TropiClean Skin & Coat Supplement',
    category: 'Health',
    petType: 'Dog',
    price: 699,
    mrp: 799,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Liquid Oil', img: 'lucide:Smile' }],
    packSizes: [{ size: '237 ml', price: 699, mrp: 799, discount: 12 }],
    description: 'Soothing liquid vitamin mixture preventing skin redness and flakes in Shih Tzus and Pugs.',
    reviewsData: { total: 124, average: 4.8, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Skin & Coat',
    proteinSource: null,
    weight: null,
    discountRange: 12,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 80,
    brand: 'EYEENVY',
    name: 'Eye Care Eyewash Solution',
    category: 'Health',
    petType: 'Dog',
    price: 399,
    mrp: 499,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Drop Bottle', img: 'lucide:Sparkles' }],
    packSizes: [{ size: '100 ml', price: 399, mrp: 499, discount: 20 }],
    description: 'Gentle sterile eyewash. Clears dust, hair strands, and tear gland blockage in Persians and Shih Tzus.',
    reviewsData: { total: 145, average: 4.8, breakdown: [82, 14, 4, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Eye Drops',
    specialDiet: 'Eye Care',
    proteinSource: null,
    weight: null,
    discountRange: 20,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 81,
    brand: 'BEAPHAR',
    name: 'Beaphar Heart Support Taurine Syrup',
    category: 'Health',
    petType: 'Dog',
    price: 999,
    mrp: 1199,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Heart Syrup', img: 'lucide:Heart' }],
    packSizes: [{ size: '150 ml', price: 999, mrp: 1199, discount: 16 }],
    description: 'Loaded with L-Carnitine and Taurine to support active heart beats. Crucial supplement for Rottweilers/Dobermans.',
    reviewsData: { total: 76, average: 4.9, breakdown: [90, 10, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Heart Support',
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 82,
    brand: 'FRONTLINE',
    name: 'Frontline Plus Tick & Flea Protection',
    category: 'Health',
    petType: 'Dog',
    price: 849,
    mrp: 999,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Spot-On', img: 'lucide:ShieldAlert' }],
    packSizes: [{ size: '1 dose', price: 849, mrp: 999, discount: 15 }],
    description: 'Spot-on treatment that kills fleas, ticks, and lice. Essential outdoor guard for Indies.',
    reviewsData: { total: 312, average: 4.8, breakdown: [85, 10, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Spot-On',
    specialDiet: 'Flea & Tick',
    proteinSource: null,
    weight: null,
    discountRange: 15,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 83,
    brand: 'HIMALAYA',
    name: 'Himalaya Multivitamin Pet Syrup',
    category: 'Health',
    petType: 'Dog',
    price: 249,
    mrp: 299,
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Multivitamins', img: 'lucide:Plus' }],
    packSizes: [{ size: '200 ml', price: 249, mrp: 299, discount: 17 }],
    description: 'Supports growth, immune system and basic vitality of Indian Pariah dogs (Indies) and local puppies.',
    reviewsData: { total: 421, average: 4.7, breakdown: [80, 15, 5, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Immunity Support',
    proteinSource: null,
    weight: null,
    discountRange: 17,
    subCategory: 'Dog Health',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 84,
    brand: 'BEAPHAR',
    name: 'Beaphar Hairball Control Paste',
    category: 'Health',
    petType: 'Cat',
    price: 349,
    mrp: 399,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Double Action Paste', img: 'lucide:Cat' }],
    packSizes: [{ size: '100 gm', price: 349, mrp: 399, discount: 12 }],
    description: 'Double action malt paste aiding hairball passage in long hair Persian cats.',
    reviewsData: { total: 115, average: 4.8, breakdown: [82, 15, 3, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Supplements',
    specialDiet: 'Hairball Control',
    proteinSource: null,
    weight: null,
    discountRange: 12,
    subCategory: 'Cat Health',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 85,
    brand: 'RUFFWEAR',
    name: 'Ruffwear Front Range No-Pull Harness',
    category: 'Accessories',
    petType: 'Dog',
    price: 2999,
    mrp: 3499,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'No-Pull Red', img: 'lucide:Circle' }],
    packSizes: [{ size: 'Medium/Large', price: 2999, mrp: 3499, discount: 14 }],
    description: 'Premium no-pull harness padded for chest and neck bones. Keeps active dogs safe.',
    reviewsData: { total: 201, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Walk Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 14,
    subCategory: 'Harnesses',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 86,
    brand: 'FLEXI',
    name: 'Flexi Giant Neon Retractable Leash',
    category: 'Accessories',
    petType: 'Dog',
    price: 1899,
    mrp: 2199,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Neon Tape', img: 'lucide:Menu' }],
    packSizes: [{ size: '8m Tape', price: 1899, mrp: 2199, discount: 13 }],
    description: 'Extends up to 8m giving dogs freedom. Comfortable handle grip and high-strength tape.',
    reviewsData: { total: 112, average: 4.8, breakdown: [80, 16, 4, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Walk Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 13,
    subCategory: 'Collars & Leashes',
    isNewArrival: false,
    isBestseller: false
  },
  {
    id: 87,
    brand: 'COMFORTPAW',
    name: 'ComfortPaw Orthopedic Memory Bed',
    category: 'Accessories',
    petType: 'Dog',
    price: 3499,
    mrp: 3999,
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Large Cushion', img: 'lucide:Bed' }],
    packSizes: [{ size: 'Large', price: 3499, mrp: 3999, discount: 12 }],
    description: 'True orthopedic support for hip joints and muscles. Cleanable zipped outer cover.',
    reviewsData: { total: 95, average: 4.9, breakdown: [90, 8, 2, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Bedding',
    specialDiet: 'Joint Care',
    proteinSource: null,
    weight: null,
    discountRange: 12,
    subCategory: 'Beds',
    isNewArrival: false,
    isBestseller: true
  },
  {
    id: 88,
    brand: 'TRAVELPAW',
    name: 'TravelPaw Safe Car Carrier Bucket',
    category: 'Accessories',
    petType: 'Dog',
    price: 2499,
    mrp: 2999,
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200',
    images: ['https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=200'],
    variants: [{ name: 'Black Bucket', img: 'lucide:Car' }],
    packSizes: [{ size: 'Medium size', price: 2499, mrp: 2999, discount: 16 }],
    description: 'Ensures safe and comfy car travel. Secures to your vehicle seat belt loops.',
    reviewsData: { total: 42, average: 4.8, breakdown: [80, 20, 0, 0, 0], reviews: [] },
    dietType: null,
    lifeStage: 'All Life Stages',
    productType: 'Travel Gear',
    specialDiet: null,
    proteinSource: null,
    weight: null,
    discountRange: 16,
    subCategory: 'Travel',
    isNewArrival: false,
    isBestseller: false
  }
];

